# Generated by Django 5.1.3 on 2024-11-12 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('class_name', 'university')},
            },
        ),
        migrations.CreateModel(
            name='FlashCardSet',
            fields=[
                ('set_id', models.AutoField(primary_key=True, serialize=False)),
                ('set_name', models.CharField(max_length=100)),
                ('class_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TestNow.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestNow.user')),
            ],
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('flash_card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestNow.flashcardset')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_done', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestNow.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('user_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestNow.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestNow.user')),
            ],
        ),
    ]
