# Generated by Django 5.1.3 on 2024-11-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestNow', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='ClassTable',
        ),
        migrations.RenameModel(
            old_name='FlashCard',
            new_name='FlashCards',
        ),
    ]
