# Generated by Django 5.1.3 on 2024-11-22 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestNow', '0003_remove_user_password_hash_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
