# Generated by Django 5.1.3 on 2024-12-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestNow', '0004_rename_user_id_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
                ('members', models.TextField()),
            ],
        ),
    ]
