# Generated by Django 5.1.3 on 2024-12-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestNow', '0005_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classtable',
            unique_together=set(),
        ),
    ]
